### ISSUE TITLE
UI/UX enhancement: remove the User tab

### ISSUE THREAD

**Issue by xan2622** [Victor-IX/Blender-Launcher-V2#121]
🟡 **Is your feature request related to a problem? Please describe.**

- Currently, the "User" tab (at the top) contains "Favorites" and "Custom" (both displayed on the left side of the UI).
UX-wise, their location is not consistent with the rest of the interface. In my opinion, there's no real need to place them inside a "User" tab. 
<img src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/1732773/34ec7195-92e3-4390-a223-b8132d428bb5" width="80%" height="80%"> 

- If you look at the Blender Launcher interface (image below <img src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/1732773/6c750ae3-4a65-4654-b34a-a24bbbce7603" width="2%" height="2%">), it seems logical to use the left side for everything related to the "type of installation". That's why I think "Custom" should also be located on the left side of the UI and "Favorites" at the top. 
<img src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/1732773/b8e46080-64bb-46be-a226-70088dd88455" width="80%" height="80%">

🟡 **Describe the solution you'd like:**

- Could you please consider to remove the "User" tab and move the "Favorites" tab to the top and the "Custom" tab to the left?
This would also save 1 click for the user: He/She would just have to directly click on "Favorites" or "Custom" rather than being forced to go inside the "User" tab first.

- Here is a mock-up of the new UI: 
<img src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/1732773/39838274-192e-4a8a-9d5d-5e687b13f2f5" width="80%" height="80%">

**Comment by Victor-IX** [comment]
What do you think about also moving the favorite tab to the left side of the Library tab? 
IMO, having the favorite tabs on the right makes it awkward to use. Having everything in the Library tab would make more sense; it would make it easier to navigate to the favorite builds.

**Comment by xan2622** [comment]
That seems logical. 👍

**Comment by xan2622** [comment]
That would do it. 👍

**Comment by xan2622** [comment]
As I said in my previous comment ⬆️, I think that **Favorites** would deserve to be placed at the top because it doesn't
 belong to "a build that is installed on the disk" (unlike Stable, Daily, Experimental and Custom). If you know what I mean.

> IMO, having the favorite tabs on the right makes it awkward to use. Having everything in the Library tab would make more sense; it would make it easier to navigate to the favorite builds.
I don't really think it would make easier to find the _Favorites_ in the _Library_ tab, rather than directly seeing it on the top row of tabs.

**Comment by baronlanteigne** [comment]
Slightly off topic but I think it makes more sense to chat about this here rather than create a new ticket.

The distinction between Library and Downloads is quite binary so it makes sense to only have 2 tabs on that axis. So shouldn't the favorite tab be on the left too? This selection will always be a sub selection of the Library anyway. (That said, it's true that there's enough space up there for a 3rd tab)

It's great to sort different versions of blenders but I usually have 3-4 versions at all time as I don't need older versions for that long. There's also no way to see everything that's installed and those 3-4 versions will get spread across 2-3 categories. (Usually Stable and Daily for me) So I often find myself having to click them all to get a better sense of what's installed on a computer. For this reason, I usually favorite everything so I use the User/Favorite tab as a way to see all of my 3-4 versions.

My actual suggestion: I just wish there was an "All" tab to see everything in one place.

**Comment by xan2622** [comment]
>  So shouldn't the favorite tab be on the left too?

 That's why Victor created a poll on the BlenderArtists thread (to let users decide): 
 https://blenderartists.org/t/blender-launcher-standalone-software-client/1230543/315

**Comment by xan2622** [comment]
Thank you for removing the User tab.
