### ISSUE TITLE
Blender 4.2.1 not available

### ISSUE THREAD

**Issue by toshicg** [Victor-IX/Blender-Launcher-V2#140]
**Describe the bug**
Blender 4.2.1 is not available under Downloads

**To Reproduce**
Go to downloads and see if 4.2.1 is available for download. In my case it isn't. 

**Expected behavior**
4.2.1 is officially released so it should be available for download.

**Screenshots**
![image](https://github.com/user-attachments/assets/91c9465e-802f-4536-b3e3-ad22837ac3c1)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 2.2.0
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Comment by zeptofine** [comment]
What you are likely seeing right now are cached links. download.blender.org is not accepting any requests made by the app at this time, so none of those links will actually work. As long as the download site is blocking our requests, we will not get up-to-date information.

BUT Since 4.2.1 is in a stable state, it shouldn't be risky to download it from the "daily" tab, where it is still available for a little bit

**Comment by Victor-IX** [comment]
The issue has been resolved!

**Comment by toshicg** [comment]
Awesome, thank! I can confirm 👍
