### ISSUE TITLE
Scraping of stable releases not working

### ISSUE THREAD

**Issue by VANN-Universal** [Victor-IX/Blender-Launcher-V2#27]
**Describe the bug**
In the download section, no stable releases are available. I get the error `Failed to gather stable releases` when running Blender Launcher through the terminal, which indicates that either the download of "https://download.blender.org/release/" failed or the filtering with BeautifulSoup. Daily and Experimental builds work as expected.

**System:**
 - Operation system: Debian 12
 - Blender Launcher version: 1.16.1

**Comment by rajeshja** [comment]
This was reported on the original launcher `issues` a couple of weeks ago as due to blender.org blocking scraping the `/release` folder. 
Since it's still not working, can we have documentation on an alternative until it gets resolved? Here's what worked for me: 
1. Download the latest build and extract it under `versions/stable`
2. Make sure the folder name is of the following format: `blender-<version>+<build-type = stable>.<commit id = I just used x64>`
3. Quit Blender Launcher and restart it (It didn't work for me without the restart)

**Comment by VANN-Universal** [comment]
I don't know what happened, but the issue solved itself over night. Blender.org has probably removed the blocking since I haven't done anything on my system.
