### ISSUE TITLE
Not working on linux mint 20.3

### ISSUE THREAD

**Issue by Ninjabdou** [Victor-IX/Blender-Launcher-V2#32]
**Describe the bug**
The app doesn't open at all on linux mint 20.3 cinnamon, I used the 1.16.0 and 1.16.1, the files are indeed executable but are not opening.
I tried to open it from the terminal and I get the following message
' [97538] Error loading Python lib '/tmp/_MEI2RrJzu/libpython3.9.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory '
I did a little google search and found some simlar problems with suggestions to install libxcrypt but nothing changed at all.
I even used sudo but it was all the same result.

**Comment by Ninjabdou** [comment]
I tried the release you provided and it didn't work and got the following message
'Error loading Python lib '/tmp/_MEIMKV8r6/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIMKV8r6/libpython3.9.so.1.0)'
I did not test it in the latest Linux release< when I do I'll let you know

**Comment by Ninjabdou** [comment]
This is not solved, it still isn't working on mint 20 and the release working on mint 21 comes from his forl and not yours.

**Comment by zeptofine** [comment]
🤔 strange, they should be the same builds
I'll try running them in a live environment

**Comment by Victor-IX** [comment]
Yes, the Ubuntu build is exactly the same between the one in the link and the one available in the last release. This is very strange with only one of them

**Comment by zeptofine** [comment]
I just tested the builds on Linux mint 20.3 and I can replicate your results. it has to deal with these versions having an old version of glibc. I'm guessing if you try either version on 21 it works fine and if you attempt to install a newer version of glibc, it should also work fine
it's curious that the old versions don't have this issue. it's probably because the built it on an older version of Ubuntu. I'll look into that

**Comment by zeptofine** [comment]
I just tested the builds on Linux mint 20.3 and I can replicate your results. it has to deal with these versions having an old version of glibc. I'm guessing if you try either version on 21 it works fine and if you attempt to install a newer version of glibc, it should also work fine
it's curious that the old versions don't have this issue. it's probably because the built it on an older version of Ubuntu. I'll look into that

**Comment by zeptofine** [comment]
yep, 21.2 has version 2.35 of glibc

**Comment by zeptofine** [comment]
The github action now builds the program in Ubuntu 20.04, and the resulting build works in my live environment. It should be fixed by the next update, or if we re-run the action it should be available soon

**Comment by zeptofine** [comment]
@Ninjabdou I've uploaded a new version of the Ubuntu build to the latest release, tell me if that fixes it for you

**Comment by Ninjabdou** [comment]
This latest updated version seems to work fine on linux mint 20.3.  Thank you very much @zeptofine @Victor-IX for your efforts to keep the development of this useful software.
