### ISSUE TITLE
Downloaded update, doesn't run

### ISSUE THREAD

**Issue by srlake31470** [Victor-IX/Blender-Launcher-V2#87]
**Describe the bug**

**To Reproduce**

**Expected behavior**
When I downloaded the zip, I then unzipped/extract all, and the Blenderlauncher icon appears but when I double click to install, nothing happens!

**Screenshots**

**System (please complete the following information):**
 - Operation system:Windows 11 Pro
 - Blender Launcher version: Attempting to install :[v2.0.24](https://github.com/Victor-IX/Blender-Launcher-V2/releases/tag/v2.0.24)
 - Log file: It's blank!

**Additional context**

**Comment by Victor-IX** [comment]
So if I understand your issue correctly after downloading the latest version of the Blender launcher, when you try to open the .exe file nothing happens?

If yes, check if your antivirus detects the Blender Launcher program as a malicious file, some antivirus are blocking the program on the last version

**Comment by danm3d** [comment]
Is there a certificate or signing step that may be needed for the binary to be flagged as OK? Or a submission to the Antimalware powers that be...
I have also tried to run the latest .exe (v2.1.24) and am encountering the same issue with Windows Defender running. I managed to get around it, but yeah, Defender swallows the execution by default. Interestingly I don't even get a Windows SmartScreen popup on run (which normally happens when running unknown .exe's)

**Comment by Victor-IX** [comment]
I sent the .exe to Microsoft to be whitelisted, so Windows Defender is supposed not to cause any issues. Last time I checked, there were only two AV with false detections, and I sent the last version to them, but no response since...
For the Windows popup on the first run, this only happens if the program is not trusty. This is removed after some time; many things can help the program to build trust (number of executions, sent to Microsoft for an AV check...)

**Comment by Victor-IX** [comment]
@srlake31470 Re-open this issue if you still need help
